<?php

namespace Database\Seeders\Questions;

class CompTIAAQuestionSeeder extends BaseQuestionSeeder
{
    protected function getCertificationSlug(): string
    {
        return 'comptia-a-plus';
    }

    protected function getQuestionsData(): array
    {
        return [
            'Hardware' => [
                // Original 3 questions
                $this->q('What type of RAM is commonly used in modern desktop computers?', [$this->correct('DDR4'), $this->wrong('DDR2'), $this->wrong('SDRAM'), $this->wrong('RDRAM')], 'DDR4 (Double Data Rate 4) is the current standard for desktop RAM, offering higher speeds and lower power consumption than previous generations.', 'easy', 'approved'),
                $this->q('Which connector is used for modern SATA hard drives?', [$this->correct('7-pin data connector'), $this->wrong('4-pin Molex'), $this->wrong('15-pin VGA'), $this->wrong('24-pin ATX')], 'SATA drives use a 7-pin data connector and a separate 15-pin power connector.', 'easy', 'approved'),
                $this->q('What is the purpose of thermal paste on a CPU?', [$this->correct('To improve heat transfer between CPU and heatsink'), $this->wrong('To insulate the CPU from electrical damage'), $this->wrong('To increase CPU clock speed'), $this->wrong('To protect against dust')], 'Thermal paste fills microscopic gaps between the CPU and heatsink, improving heat transfer efficiency.', 'medium', 'approved'),
                
                // New 30 questions
                $this->q('Which type of memory module uses 288 pins and is commonly found in modern desktop computers?', [$this->correct('DDR4 SDRAM'), $this->wrong('DDR3 SDRAM'), $this->wrong('DDR2 SDRAM'), $this->wrong('SODIMM')], 'DDR4 SDRAM uses 288 pins for desktop modules, while DDR3 uses 240 pins. SODIMMs are laptop memory modules.', 'easy', 'approved'),
                $this->q('What is the maximum data transfer rate of a SATA III interface?', [$this->correct('6 Gbps'), $this->wrong('3 Gbps'), $this->wrong('12 Gbps'), $this->wrong('1.5 Gbps')], 'SATA III (SATA 6Gb/s) supports transfer rates up to 6 Gbps, which is double that of SATA II.', 'medium', 'approved'),
                $this->q('Which power connector is used to supply power to modern graphics cards requiring additional power?', [$this->correct('6-pin or 8-pin PCIe'), $this->wrong('4-pin Molex'), $this->wrong('24-pin ATX'), $this->wrong('SATA power')], 'High-performance graphics cards use 6-pin or 8-pin PCIe power connectors to supplement power from the PCIe slot.', 'medium', 'approved'),
                $this->q('What is the primary purpose of the CMOS battery on a motherboard?', [$this->correct('Maintain BIOS settings when the computer is off'), $this->wrong('Power the CPU during boot'), $this->wrong('Provide backup power for RAM'), $this->wrong('Power the cooling fans')], 'The CMOS battery maintains BIOS/UEFI settings and the system clock when the computer is powered off.', 'easy', 'approved'),
                $this->q('Which form factor motherboard measures 12" × 9.6" and is commonly used in full-tower cases?', [$this->correct('ATX'), $this->wrong('Mini-ITX'), $this->wrong('Micro-ATX'), $this->wrong('E-ATX')], 'ATX (Advanced Technology eXtended) motherboards measure 12" × 9.6" and are the standard for full-tower and mid-tower cases.', 'easy', 'approved'),
                $this->q('What is the maximum theoretical bandwidth of a PCIe 3.0 x16 slot?', [$this->correct('16 GB/s'), $this->wrong('8 GB/s'), $this->wrong('32 GB/s'), $this->wrong('4 GB/s')], 'PCIe 3.0 provides approximately 1 GB/s per lane. A x16 slot therefore provides roughly 16 GB/s of bandwidth.', 'hard', 'approved'),
                $this->q('Which CPU socket type is used by Intel\'s 12th generation (Alder Lake) processors?', [$this->correct('LGA 1700'), $this->wrong('LGA 1200'), $this->wrong('AM4'), $this->wrong('LGA 1151')], 'Intel\'s 12th generation processors use the LGA 1700 socket, which replaced LGA 1200.', 'medium', 'approved'),
                $this->q('What does the term "dual-channel memory" refer to?', [$this->correct('Installing RAM in pairs to increase bandwidth'), $this->wrong('Using two different types of RAM'), $this->wrong('RAM with two separate voltage rails'), $this->wrong('Memory that operates at two different speeds')], 'Dual-channel memory architecture uses two memory modules working in parallel to double the data transfer rate.', 'medium', 'approved'),
                $this->q('Which type of cooling solution uses a liquid coolant to transfer heat away from the CPU?', [$this->correct('Liquid cooling system'), $this->wrong('Heat sink'), $this->wrong('Case fan'), $this->wrong('Thermal pad')], 'Liquid cooling systems (AIO or custom loops) use liquid coolant to efficiently transfer heat from the CPU to a radiator.', 'easy', 'approved'),
                $this->q('What is the standard voltage for DDR4 RAM?', [$this->correct('1.2V'), $this->wrong('1.5V'), $this->wrong('1.35V'), $this->wrong('1.65V')], 'DDR4 RAM operates at 1.2V, which is lower than DDR3\'s 1.5V, resulting in better power efficiency.', 'medium', 'approved'),
                $this->q('Which storage interface provides the fastest data transfer speeds for modern SSDs?', [$this->correct('NVMe over PCIe'), $this->wrong('SATA III'), $this->wrong('USB 3.0'), $this->wrong('eSATA')], 'NVMe (Non-Volatile Memory Express) over PCIe provides significantly faster speeds than SATA III, with modern drives reaching 7000+ MB/s.', 'medium', 'approved'),
                $this->q('What is the purpose of ECC (Error-Correcting Code) memory?', [$this->correct('Detect and correct memory errors'), $this->wrong('Increase memory speed'), $this->wrong('Reduce power consumption'), $this->wrong('Enable dual-channel operation')], 'ECC memory can detect and correct single-bit errors, making it essential for servers and mission-critical applications.', 'medium', 'approved'),
                $this->q('Which component is responsible for converting AC power from the wall outlet to DC power for computer components?', [$this->correct('Power Supply Unit (PSU)'), $this->wrong('Motherboard'), $this->wrong('UPS'), $this->wrong('Voltage regulator')], 'The PSU converts AC power to DC power at various voltages (3.3V, 5V, 12V) required by computer components.', 'easy', 'approved'),
                $this->q('What does the 80 PLUS certification indicate for a power supply?', [$this->correct('Energy efficiency rating'), $this->wrong('Maximum wattage output'), $this->wrong('Number of connectors'), $this->wrong('Warranty period')], '80 PLUS certification indicates that a PSU is at least 80% efficient at converting AC to DC power under typical loads.', 'medium', 'approved'),
                $this->q('Which M.2 form factor is 80mm long and 22mm wide?', [$this->correct('2280'), $this->wrong('2242'), $this->wrong('2260'), $this->wrong('22110')], 'M.2 2280 indicates a width of 22mm and length of 80mm, the most common size for M.2 SSDs.', 'medium', 'approved'),
                $this->q('What is the primary advantage of an SSD over a traditional HDD?', [$this->correct('Faster data access speeds'), $this->wrong('Larger storage capacity'), $this->wrong('Lower cost per gigabyte'), $this->wrong('Better for long-term archival')], 'SSDs have no moving parts and use flash memory, providing significantly faster read/write speeds compared to HDDs.', 'easy', 'approved'),
                $this->q('Which RAID level provides disk striping without redundancy?', [$this->correct('RAID 0'), $this->wrong('RAID 1'), $this->wrong('RAID 5'), $this->wrong('RAID 10')], 'RAID 0 stripes data across multiple disks for performance but provides no redundancy. If one disk fails, all data is lost.', 'medium', 'approved'),
                $this->q('What is the maximum length of a standard DisplayPort cable before signal degradation occurs?', [$this->correct('15 meters'), $this->wrong('5 meters'), $this->wrong('10 meters'), $this->wrong('20 meters')], 'DisplayPort cables can reliably transmit signals up to 15 meters (49 feet) without active amplification.', 'hard', 'approved'),
                $this->q('Which type of printer uses a heated print head to transfer ink from a ribbon onto paper?', [$this->correct('Thermal'), $this->wrong('Inkjet'), $this->wrong('Laser'), $this->wrong('Dot matrix')], 'Thermal printers use heat to transfer ink from a ribbon or directly onto heat-sensitive paper.', 'medium', 'approved'),
                $this->q('What is the typical RPM (revolutions per minute) of a high-performance desktop hard drive?', [$this->correct('7200 RPM'), $this->wrong('5400 RPM'), $this->wrong('10000 RPM'), $this->wrong('15000 RPM')], 'Most desktop HDDs operate at 7200 RPM, balancing performance and cost. 5400 RPM is common for laptops and budget drives.', 'easy', 'approved'),
                $this->q('Which USB standard supports data transfer rates up to 10 Gbps?', [$this->correct('USB 3.1 Gen 2'), $this->wrong('USB 2.0'), $this->wrong('USB 3.0'), $this->wrong('USB 1.1')], 'USB 3.1 Gen 2 (also known as USB 3.2 Gen 2) supports speeds up to 10 Gbps, double that of USB 3.0.', 'medium', 'approved'),
                $this->q('What is the primary function of a KVM switch?', [$this->correct('Control multiple computers with one keyboard, video, and mouse'), $this->wrong('Share internet connection between computers'), $this->wrong('Switch between different operating systems'), $this->wrong('Manage virtual machines')], 'A KVM (Keyboard, Video, Mouse) switch allows one set of peripherals to control multiple computers.', 'easy', 'approved'),
                $this->q('Which component on a motherboard provides the interface between the CPU and RAM?', [$this->correct('Northbridge/Memory Controller'), $this->wrong('Southbridge'), $this->wrong('BIOS chip'), $this->wrong('PCIe controller')], 'The Northbridge (or integrated memory controller in modern CPUs) manages communication between the CPU and RAM.', 'medium', 'approved'),
                $this->q('What is the maximum resolution supported by HDMI 2.0?', [$this->correct('3840×2160 at 60Hz'), $this->wrong('1920×1080 at 60Hz'), $this->wrong('3840×2160 at 30Hz'), $this->wrong('7680×4320 at 60Hz')], 'HDMI 2.0 supports 4K (3840×2160) resolution at 60Hz. HDMI 2.1 is required for 8K or higher refresh rates.', 'medium', 'approved'),
                $this->q('Which type of expansion card is specifically designed to add additional USB ports to a computer?', [$this->correct('USB expansion card'), $this->wrong('Network interface card'), $this->wrong('Sound card'), $this->wrong('Graphics card')], 'USB expansion cards (PCIe or PCI) add additional USB ports when motherboard ports are insufficient.', 'easy', 'approved'),
                $this->q('What does TPM stand for in computer security?', [$this->correct('Trusted Platform Module'), $this->wrong('Total Protection Module'), $this->wrong('Thermal Protection Mechanism'), $this->wrong('Transfer Protocol Manager')], 'TPM is a dedicated microcontroller designed to secure hardware through integrated cryptographic keys.', 'medium', 'approved'),
                $this->q('Which type of RAM is commonly used in laptops due to its smaller form factor?', [$this->correct('SODIMM'), $this->wrong('DIMM'), $this->wrong('RIMM'), $this->wrong('SIMM')], 'SODIMM (Small Outline Dual In-line Memory Module) is the standard memory format for laptops and compact systems.', 'easy', 'approved'),
                $this->q('What is the purpose of the heatsink on a CPU?', [$this->correct('Dissipate heat away from the CPU'), $this->wrong('Increase processing speed'), $this->wrong('Protect the CPU from physical damage'), $this->wrong('Reduce electrical interference')], 'A heatsink uses metal fins to increase surface area and dissipate heat generated by the CPU to prevent overheating.', 'easy', 'approved'),
                $this->q('Which BIOS/UEFI setting allows you to change the boot order of devices?', [$this->correct('Boot sequence/Boot priority'), $this->wrong('Advanced settings'), $this->wrong('Security settings'), $this->wrong('Power management')], 'The boot sequence or boot priority setting determines which device the system attempts to boot from first.', 'easy', 'approved'),
                $this->q('What is the typical wattage requirement for a gaming PC with a high-end graphics card?', [$this->correct('650-850W'), $this->wrong('300-400W'), $this->wrong('450-550W'), $this->wrong('1000-1200W')], 'Gaming PCs with high-end GPUs typically require 650-850W PSUs to provide adequate power with headroom for stability.', 'medium', 'approved'),
            ],
            
            'Networking' => [
                // Original 3 questions
                $this->q('What is the maximum cable length for Cat6 Ethernet at 1 Gbps?', [$this->correct('100 meters (328 feet)'), $this->wrong('50 meters'), $this->wrong('200 meters'), $this->wrong('500 meters')], 'Cat6 cable supports 1 Gbps up to 100 meters, which is the standard for structured cabling.', 'medium', 'approved'),
                $this->q('Which IP address is a private address?', [$this->correct('192.168.1.1'), $this->wrong('8.8.8.8'), $this->wrong('1.1.1.1'), $this->wrong('208.67.222.222')], 'Private IP ranges include 10.0.0.0/8, 172.16.0.0/12, and 192.168.0.0/16. These are not routable on the internet.', 'easy', 'approved'),
                $this->q('What does DHCP stand for?', [$this->correct('Dynamic Host Configuration Protocol'), $this->wrong('Direct Host Control Protocol'), $this->wrong('Dynamic Hardware Configuration Protocol'), $this->wrong('Direct Hardware Control Protocol')], 'DHCP automatically assigns IP addresses and network configuration to devices on a network.', 'easy', 'approved'),
                
                // New 30 questions
                $this->q('What is the default subnet mask for a Class C IP address?', [$this->correct('255.255.255.0'), $this->wrong('255.0.0.0'), $this->wrong('255.255.0.0'), $this->wrong('255.255.255.255')], 'Class C networks use a /24 subnet mask (255.255.255.0), providing 254 usable host addresses.', 'medium', 'approved'),
                $this->q('Which port number does HTTPS use by default?', [$this->correct('443'), $this->wrong('80'), $this->wrong('8080'), $this->wrong('21')], 'HTTPS (HTTP Secure) uses port 443 by default, while HTTP uses port 80.', 'easy', 'approved'),
                $this->q('What does DNS stand for?', [$this->correct('Domain Name System'), $this->wrong('Dynamic Network Service'), $this->wrong('Digital Network Security'), $this->wrong('Direct Name Server')], 'DNS translates human-readable domain names (like google.com) into IP addresses that computers use.', 'easy', 'approved'),
                $this->q('Which network topology connects all devices to a central hub or switch?', [$this->correct('Star topology'), $this->wrong('Bus topology'), $this->wrong('Ring topology'), $this->wrong('Mesh topology')], 'Star topology connects all devices to a central point, making it easy to add/remove devices and isolate failures.', 'easy', 'approved'),
                $this->q('What is the maximum cable length for Cat6 Ethernet at 10 Gbps?', [$this->correct('55 meters'), $this->wrong('100 meters'), $this->wrong('150 meters'), $this->wrong('328 feet')], 'Cat6 can support 10 Gbps speeds up to 55 meters. For the full 100 meters, Cat6a is required.', 'medium', 'approved'),
                $this->q('Which protocol is used to automatically assign IP addresses to devices on a network?', [$this->correct('DHCP'), $this->wrong('DNS'), $this->wrong('FTP'), $this->wrong('SMTP')], 'DHCP (Dynamic Host Configuration Protocol) automatically assigns IP addresses and network configuration to devices.', 'easy', 'approved'),
                $this->q('What is the purpose of a subnet mask?', [$this->correct('Determine network and host portions of an IP address'), $this->wrong('Encrypt network traffic'), $this->wrong('Filter unwanted network traffic'), $this->wrong('Assign IP addresses automatically')], 'A subnet mask divides an IP address into network and host portions, determining which devices are on the same subnet.', 'medium', 'approved'),
                $this->q('Which wireless standard operates exclusively in the 5 GHz frequency band?', [$this->correct('802.11ac'), $this->wrong('802.11b'), $this->wrong('802.11g'), $this->wrong('802.11n')], '802.11ac (Wi-Fi 5) operates only in the 5 GHz band, while 802.11n can use both 2.4 GHz and 5 GHz.', 'medium', 'approved'),
                $this->q('What does NAT stand for in networking?', [$this->correct('Network Address Translation'), $this->wrong('Network Access Token'), $this->wrong('Network Authentication Tool'), $this->wrong('Network Allocation Table')], 'NAT translates private IP addresses to public IP addresses, allowing multiple devices to share a single public IP.', 'medium', 'approved'),
                $this->q('Which command is used to test network connectivity between two devices?', [$this->correct('ping'), $this->wrong('ipconfig'), $this->wrong('tracert'), $this->wrong('netstat')], 'The ping command sends ICMP echo requests to test connectivity and measure round-trip time to a destination.', 'easy', 'approved'),
                $this->q('What is the maximum theoretical speed of 802.11ac (Wi-Fi 5)?', [$this->correct('3.5 Gbps'), $this->wrong('600 Mbps'), $this->wrong('1.3 Gbps'), $this->wrong('9.6 Gbps')], '802.11ac can theoretically reach speeds up to 3.5 Gbps with 8 spatial streams, though typical speeds are much lower.', 'medium', 'approved'),
                $this->q('Which network device operates at Layer 3 of the OSI model?', [$this->correct('Router'), $this->wrong('Hub'), $this->wrong('Switch'), $this->wrong('Bridge')], 'Routers operate at Layer 3 (Network Layer), making routing decisions based on IP addresses.', 'medium', 'approved'),
                $this->q('What is the purpose of a firewall?', [$this->correct('Filter and control network traffic based on security rules'), $this->wrong('Boost network speed'), $this->wrong('Assign IP addresses'), $this->wrong('Convert domain names to IP addresses')], 'Firewalls monitor and control incoming and outgoing network traffic based on predetermined security rules.', 'easy', 'approved'),
                $this->q('Which IP address range is reserved for private networks?', [$this->correct('10.0.0.0 to 10.255.255.255'), $this->wrong('11.0.0.0 to 11.255.255.255'), $this->wrong('9.0.0.0 to 9.255.255.255'), $this->wrong('8.0.0.0 to 8.255.255.255')], 'The 10.0.0.0/8 range (10.0.0.0 to 10.255.255.255) is one of three private IP address ranges defined in RFC 1918.', 'medium', 'approved'),
                $this->q('What does VPN stand for?', [$this->correct('Virtual Private Network'), $this->wrong('Verified Public Network'), $this->wrong('Virtual Protected Node'), $this->wrong('Verified Private Node')], 'A VPN creates a secure, encrypted connection over a less secure network, such as the internet.', 'easy', 'approved'),
                $this->q('Which port does FTP use for data transfer by default?', [$this->correct('20'), $this->wrong('21'), $this->wrong('22'), $this->wrong('23')], 'FTP uses port 21 for control commands and port 20 for data transfer in active mode.', 'hard', 'approved'),
                $this->q('What is the purpose of QoS (Quality of Service) in networking?', [$this->correct('Prioritize certain types of network traffic'), $this->wrong('Encrypt network traffic'), $this->wrong('Increase bandwidth'), $this->wrong('Block malicious traffic')], 'QoS prioritizes certain traffic types (like VoIP or video) to ensure consistent performance for critical applications.', 'medium', 'approved'),
                $this->q('Which cable type is immune to electromagnetic interference?', [$this->correct('Fiber optic cable'), $this->wrong('Unshielded Twisted Pair (UTP)'), $this->wrong('Coaxial cable'), $this->wrong('Shielded Twisted Pair (STP)')], 'Fiber optic cables use light instead of electrical signals, making them completely immune to EMI.', 'medium', 'approved'),
                $this->q('What does PoE stand for in networking?', [$this->correct('Power over Ethernet'), $this->wrong('Protocol over Ethernet'), $this->wrong('Port of Entry'), $this->wrong('Packet over Ethernet')], 'PoE allows network cables to carry electrical power along with data, useful for IP cameras and wireless access points.', 'easy', 'approved'),
                $this->q('Which protocol is used to securely transfer files over a network?', [$this->correct('SFTP'), $this->wrong('FTP'), $this->wrong('HTTP'), $this->wrong('Telnet')], 'SFTP (SSH File Transfer Protocol) provides secure file transfer with encryption, unlike standard FTP.', 'medium', 'approved'),
                $this->q('What is the loopback IP address used for testing network software?', [$this->correct('127.0.0.1'), $this->wrong('192.168.1.1'), $this->wrong('0.0.0.0'), $this->wrong('255.255.255.255')], '127.0.0.1 is the loopback address that routes traffic back to the local machine for testing purposes.', 'easy', 'approved'),
                $this->q('Which wireless encryption standard is considered most secure?', [$this->correct('WPA3'), $this->wrong('WEP'), $this->wrong('WPA'), $this->wrong('WPA2')], 'WPA3 is the latest and most secure Wi-Fi encryption standard, addressing vulnerabilities in WPA2.', 'medium', 'approved'),
                $this->q('What is the purpose of VLAN (Virtual Local Area Network)?', [$this->correct('Segment a network into logical groups'), $this->wrong('Increase network speed'), $this->wrong('Provide wireless connectivity'), $this->wrong('Encrypt network traffic')], 'VLANs logically segment a network to improve security, reduce broadcast traffic, and organize devices.', 'medium', 'approved'),
                $this->q('Which command displays the routing table on a Windows computer?', [$this->correct('route print'), $this->wrong('ipconfig'), $this->wrong('netstat'), $this->wrong('tracert')], 'The "route print" command displays the current routing table, showing how packets are directed to different networks.', 'medium', 'approved'),
                $this->q('What is the maximum distance for a 10GBase-T Ethernet connection using Cat6a cable?', [$this->correct('100 meters'), $this->wrong('55 meters'), $this->wrong('150 meters'), $this->wrong('200 meters')], 'Cat6a cable can support 10 Gbps Ethernet (10GBase-T) for the full 100-meter distance specification.', 'hard', 'approved'),
                $this->q('Which network device amplifies and retransmits signals to extend network range?', [$this->correct('Repeater'), $this->wrong('Switch'), $this->wrong('Router'), $this->wrong('Bridge')], 'A repeater amplifies and regenerates signals to extend the distance a signal can travel on a network.', 'easy', 'approved'),
                $this->q('What does MTU stand for in networking?', [$this->correct('Maximum Transmission Unit'), $this->wrong('Maximum Transfer Unit'), $this->wrong('Minimum Transfer Unit'), $this->wrong('Multiple Transmission Unit')], 'MTU is the largest size packet or frame that can be sent in a single network transaction, typically 1500 bytes for Ethernet.', 'medium', 'approved'),
                $this->q('Which protocol is used to synchronize time across network devices?', [$this->correct('NTP'), $this->wrong('SMTP'), $this->wrong('SNMP'), $this->wrong('DNS')], 'NTP (Network Time Protocol) synchronizes clocks of computer systems over packet-switched networks.', 'medium', 'approved'),
                $this->q('What is the purpose of ARP (Address Resolution Protocol)?', [$this->correct('Map IP addresses to MAC addresses'), $this->wrong('Assign IP addresses automatically'), $this->wrong('Resolve domain names to IP addresses'), $this->wrong('Encrypt network traffic')], 'ARP resolves IP addresses to MAC addresses, enabling communication at the data link layer.', 'hard', 'approved'),
                $this->q('Which port does SSH use by default?', [$this->correct('22'), $this->wrong('20'), $this->wrong('21'), $this->wrong('23')], 'SSH (Secure Shell) uses port 22 by default for secure remote access and file transfers.', 'medium', 'approved'),
            ],
            
            'Mobile Devices' => [
                // Original 3 questions
                $this->q('What type of display technology is commonly used in modern smartphones?', [$this->correct('OLED or AMOLED'), $this->wrong('CRT'), $this->wrong('Plasma'), $this->wrong('E-ink')], 'OLED (Organic Light-Emitting Diode) and AMOLED (Active Matrix OLED) are common in smartphones due to their vibrant colors and thin profile.', 'easy', 'approved'),
                $this->q('What is the purpose of airplane mode on a mobile device?', [$this->correct('To disable all wireless communications'), $this->wrong('To increase battery life only'), $this->wrong('To enable flight tracking'), $this->wrong('To activate GPS only')], 'Airplane mode disables cellular, Wi-Fi, and Bluetooth to comply with airline regulations and prevent interference.', 'easy', 'approved'),
                $this->q('Which mobile device feature allows contactless payments?', [$this->correct('NFC (Near Field Communication)'), $this->wrong('Bluetooth'), $this->wrong('Wi-Fi'), $this->wrong('Infrared')], 'NFC enables contactless payments like Apple Pay and Google Pay by communicating with payment terminals at close range.', 'medium', 'approved'),
                
                // New 30 questions
                $this->q('Which mobile device feature uses electromagnetic fields to enable contactless payments?', [$this->correct('NFC'), $this->wrong('Bluetooth'), $this->wrong('Wi-Fi'), $this->wrong('GPS')], 'NFC (Near Field Communication) enables contactless payments like Apple Pay and Google Pay within a few centimeters.', 'easy', 'approved'),
                $this->q('What is the primary purpose of airplane mode on a mobile device?', [$this->correct('Disable all wireless communications'), $this->wrong('Increase battery life'), $this->wrong('Improve GPS accuracy'), $this->wrong('Enable flight tracking')], 'Airplane mode disables all wireless radios (cellular, Wi-Fi, Bluetooth) to comply with airline regulations.', 'easy', 'approved'),
                $this->q('Which type of display technology is commonly used in modern smartphones for better color and contrast?', [$this->correct('OLED/AMOLED'), $this->wrong('LCD'), $this->wrong('TN'), $this->wrong('CRT')], 'OLED and AMOLED displays offer superior contrast, deeper blacks, and better color reproduction than LCD.', 'medium', 'approved'),
                $this->q('What does MDM stand for in mobile device management?', [$this->correct('Mobile Device Management'), $this->wrong('Mobile Data Manager'), $this->wrong('Multiple Device Monitor'), $this->wrong('Mobile Deployment Module')], 'MDM solutions allow organizations to manage, secure, and enforce policies on mobile devices.', 'medium', 'approved'),
                $this->q('Which connector type is used by most modern Android devices for charging and data transfer?', [$this->correct('USB-C'), $this->wrong('Lightning'), $this->wrong('Micro-USB'), $this->wrong('Mini-USB')], 'USB-C is the standard connector for modern Android devices, offering faster charging and data transfer.', 'easy', 'approved'),
                $this->q('What is the purpose of a digitizer in a touchscreen device?', [$this->correct('Convert touch input into digital signals'), $this->wrong('Display images on screen'), $this->wrong('Provide haptic feedback'), $this->wrong('Protect the screen from damage')], 'The digitizer is a layer that detects touch input and converts it into digital coordinates for the device to process.', 'medium', 'approved'),
                $this->q('Which mobile OS feature allows apps to run in the background with limited functionality to save battery?', [$this->correct('Battery optimization/Doze mode'), $this->wrong('Background refresh'), $this->wrong('App sandboxing'), $this->wrong('Push notifications')], 'Battery optimization features like Android\'s Doze mode limit background activity to extend battery life.', 'medium', 'approved'),
                $this->q('What is the typical battery capacity range for modern smartphones?', [$this->correct('3000-5000 mAh'), $this->wrong('1000-2000 mAh'), $this->wrong('6000-8000 mAh'), $this->wrong('500-1000 mAh')], 'Most modern smartphones have batteries ranging from 3000 to 5000 mAh, balancing size and battery life.', 'medium', 'approved'),
                $this->q('Which technology allows a smartphone to determine its location using satellites?', [$this->correct('GPS'), $this->wrong('Bluetooth'), $this->wrong('Wi-Fi'), $this->wrong('NFC')], 'GPS (Global Positioning System) uses satellite signals to determine precise location coordinates.', 'easy', 'approved'),
                $this->q('What is the purpose of a SIM card in a mobile device?', [$this->correct('Identify the subscriber to the cellular network'), $this->wrong('Store photos and videos'), $this->wrong('Increase processing power'), $this->wrong('Enable Wi-Fi connectivity')], 'A SIM (Subscriber Identity Module) card stores subscriber information and authenticates the device to the cellular network.', 'easy', 'approved'),
                $this->q('Which mobile device feature provides tactile feedback when touching the screen?', [$this->correct('Haptic feedback'), $this->wrong('Accelerometer'), $this->wrong('Gyroscope'), $this->wrong('Proximity sensor')], 'Haptic feedback uses vibrations to provide physical responses to touch interactions on the screen.', 'easy', 'approved'),
                $this->q('What is the difference between eSIM and traditional SIM cards?', [$this->correct('eSIM is embedded and programmable'), $this->wrong('eSIM is larger'), $this->wrong('eSIM only works with 5G'), $this->wrong('eSIM is removable')], 'eSIM (embedded SIM) is built into the device and can be programmed remotely, eliminating the need for physical SIM cards.', 'medium', 'approved'),
                $this->q('Which sensor detects the orientation and rotation of a mobile device?', [$this->correct('Gyroscope'), $this->wrong('Accelerometer'), $this->wrong('Magnetometer'), $this->wrong('Barometer')], 'A gyroscope measures angular velocity and rotation, enabling features like screen rotation and gaming controls.', 'medium', 'approved'),
                $this->q('What is the purpose of the proximity sensor on a smartphone?', [$this->correct('Detect when the phone is near your face during calls'), $this->wrong('Measure distance to objects'), $this->wrong('Enable facial recognition'), $this->wrong('Improve camera focus')], 'The proximity sensor detects when the phone is near your face during calls to turn off the display and prevent accidental touches.', 'medium', 'approved'),
                $this->q('Which mobile device feature allows wireless audio streaming to headphones?', [$this->correct('Bluetooth'), $this->wrong('NFC'), $this->wrong('Wi-Fi Direct'), $this->wrong('Infrared')], 'Bluetooth enables wireless audio streaming to headphones, speakers, and car audio systems.', 'easy', 'approved'),
                $this->q('What does IP68 rating indicate for a mobile device?', [$this->correct('Dust and water resistance'), $this->wrong('Internet Protocol version'), $this->wrong('Battery capacity'), $this->wrong('Screen brightness')], 'IP68 means the device is dust-tight and can withstand continuous immersion in water beyond 1 meter.', 'medium', 'approved'),
                $this->q('Which charging technology allows wireless charging of mobile devices?', [$this->correct('Qi wireless charging'), $this->wrong('USB-C'), $this->wrong('Lightning'), $this->wrong('Fast charging')], 'Qi is the industry standard for wireless charging, using electromagnetic induction to transfer power.', 'easy', 'approved'),
                $this->q('What is the purpose of a mobile device\'s ambient light sensor?', [$this->correct('Automatically adjust screen brightness'), $this->wrong('Enable night mode'), $this->wrong('Improve camera quality'), $this->wrong('Detect motion')], 'The ambient light sensor measures surrounding light levels to automatically adjust screen brightness for optimal viewing.', 'medium', 'approved'),
                $this->q('Which mobile OS security feature encrypts data stored on the device?', [$this->correct('Full disk encryption'), $this->wrong('Screen lock'), $this->wrong('App permissions'), $this->wrong('Firewall')], 'Full disk encryption (or file-based encryption) protects data by encrypting all information stored on the device.', 'medium', 'approved'),
                $this->q('What is the typical refresh rate of modern smartphone displays?', [$this->correct('60Hz or 90Hz/120Hz'), $this->wrong('30Hz'), $this->wrong('144Hz'), $this->wrong('240Hz')], 'Most smartphones use 60Hz displays, while premium models offer 90Hz, 120Hz, or even 144Hz for smoother scrolling.', 'medium', 'approved'),
                $this->q('Which biometric authentication method scans the unique patterns of your finger?', [$this->correct('Fingerprint scanner'), $this->wrong('Face ID'), $this->wrong('Iris scanner'), $this->wrong('Voice recognition')], 'Fingerprint scanners (capacitive or ultrasonic) read the unique ridge patterns on your fingertip for authentication.', 'easy', 'approved'),
                $this->q('What is the purpose of mobile device tethering?', [$this->correct('Share mobile data connection with other devices'), $this->wrong('Charge other devices'), $this->wrong('Sync contacts'), $this->wrong('Transfer files')], 'Tethering allows a mobile device to share its cellular data connection with other devices via Wi-Fi, USB, or Bluetooth.', 'easy', 'approved'),
                $this->q('Which mobile device component is responsible for processing graphics and video?', [$this->correct('GPU'), $this->wrong('CPU'), $this->wrong('RAM'), $this->wrong('Storage')], 'The GPU (Graphics Processing Unit) handles graphics rendering, video playback, and gaming performance.', 'medium', 'approved'),
                $this->q('What does the term "phablet" refer to?', [$this->correct('A large smartphone between phone and tablet size'), $this->wrong('A tablet with phone capabilities'), $this->wrong('A foldable phone'), $this->wrong('A phone with stylus support')], 'A phablet is a smartphone with a screen size typically between 5.5 and 7 inches, bridging phones and tablets.', 'easy', 'approved'),
                $this->q('Which mobile device feature allows screen mirroring to a TV or monitor?', [$this->correct('Miracast/AirPlay/Chromecast'), $this->wrong('Bluetooth'), $this->wrong('NFC'), $this->wrong('USB-C')], 'Technologies like Miracast, AirPlay, and Chromecast enable wireless screen mirroring to compatible displays.', 'medium', 'approved'),
                $this->q('What is the purpose of a mobile device\'s accelerometer?', [$this->correct('Detect motion and orientation'), $this->wrong('Measure temperature'), $this->wrong('Measure air pressure'), $this->wrong('Detect magnetic fields')], 'An accelerometer measures acceleration forces, enabling features like step counting, screen rotation, and gaming controls.', 'medium', 'approved'),
                $this->q('Which mobile OS feature isolates apps from each other for security?', [$this->correct('Sandboxing'), $this->wrong('Encryption'), $this->wrong('VPN'), $this->wrong('Firewall')], 'App sandboxing isolates applications from each other and the system, preventing malicious apps from accessing other app data.', 'hard', 'approved'),
                $this->q('What is the typical screen resolution category for modern flagship smartphones?', [$this->correct('Quad HD (1440p) or higher'), $this->wrong('HD (720p)'), $this->wrong('Full HD (1080p)'), $this->wrong('4K (2160p)')], 'Flagship smartphones typically feature Quad HD (1440p) or higher resolutions for sharp, detailed displays.', 'medium', 'approved'),
                $this->q('Which mobile device feature allows unlocking using facial recognition?', [$this->correct('Face ID/Face Unlock'), $this->wrong('Touch ID'), $this->wrong('Pattern lock'), $this->wrong('PIN code')], 'Face ID (iOS) and Face Unlock (Android) use facial recognition technology to authenticate users.', 'easy', 'approved'),
                $this->q('What is the purpose of mobile device roaming?', [$this->correct('Use cellular service outside your carrier\'s network'), $this->wrong('Switch between Wi-Fi networks'), $this->wrong('Share internet connection'), $this->wrong('Enable international calling')], 'Roaming allows your device to connect to other carriers\' networks when outside your home network\'s coverage area.', 'medium', 'approved'),
            ],
            
            'Virtualization and Cloud' => [
                // Original 3 questions
                $this->q('What is a hypervisor?', [$this->correct('Software that creates and manages virtual machines'), $this->wrong('A high-speed processor'), $this->wrong('A type of cloud storage'), $this->wrong('A network switch')], 'A hypervisor (or Virtual Machine Monitor) creates and runs virtual machines, allowing multiple operating systems to run on a single physical machine.', 'easy', 'approved'),
                $this->q('What is the difference between Type 1 and Type 2 hypervisors?', [$this->correct('Type 1 runs directly on hardware, Type 2 runs on a host OS'), $this->wrong('Type 1 is slower than Type 2'), $this->wrong('Type 2 is more secure than Type 1'), $this->wrong('They are the same')], 'Type 1 (bare-metal) hypervisors run directly on hardware (VMware ESXi, Hyper-V), while Type 2 run on a host OS (VirtualBox, VMware Workstation).', 'medium', 'approved'),
                $this->q('What is IaaS in cloud computing?', [$this->correct('Infrastructure as a Service'), $this->wrong('Internet as a Service'), $this->wrong('Integration as a Service'), $this->wrong('Information as a Service')], 'IaaS provides virtualized computing resources over the internet, including virtual machines, storage, and networks.', 'easy', 'approved'),
                
                // New 30 questions
                $this->q('What is a hypervisor?', [$this->correct('Software that creates and manages virtual machines'), $this->wrong('A high-performance processor'), $this->wrong('A cloud storage service'), $this->wrong('A network security device')], 'A hypervisor (or virtual machine monitor) creates and manages virtual machines, allowing multiple OS instances on one physical machine.', 'easy', 'approved'),
                $this->q('What is the main difference between Type 1 and Type 2 hypervisors?', [$this->correct('Type 1 runs directly on hardware, Type 2 runs on an OS'), $this->wrong('Type 1 is slower than Type 2'), $this->wrong('Type 1 is for desktops, Type 2 is for servers'), $this->wrong('Type 1 is free, Type 2 is commercial')], 'Type 1 (bare-metal) hypervisors run directly on hardware, while Type 2 hypervisors run on top of a host operating system.', 'medium', 'approved'),
                $this->q('What does IaaS stand for in cloud computing?', [$this->correct('Infrastructure as a Service'), $this->wrong('Internet as a Service'), $this->wrong('Integration as a Service'), $this->wrong('Information as a Service')], 'IaaS provides virtualized computing resources over the internet, including servers, storage, and networking.', 'easy', 'approved'),
                $this->q('Which cloud service model provides a platform for developers to build and deploy applications?', [$this->correct('PaaS'), $this->wrong('IaaS'), $this->wrong('SaaS'), $this->wrong('DaaS')], 'PaaS (Platform as a Service) provides a development and deployment environment in the cloud.', 'medium', 'approved'),
                $this->q('What is the primary benefit of server virtualization?', [$this->correct('Better hardware consolidation and resource utilization'), $this->wrong('Faster internet speeds'), $this->wrong('Cheaper hardware costs'), $this->wrong('Improved graphics performance')], 'Virtualization allows multiple virtual servers to run on one physical server, improving resource utilization and reducing costs.', 'medium', 'approved'),
                $this->q('Which cloud deployment model is owned and operated by a single organization?', [$this->correct('Private cloud'), $this->wrong('Public cloud'), $this->wrong('Hybrid cloud'), $this->wrong('Community cloud')], 'A private cloud is dedicated to a single organization, offering greater control and security.', 'medium', 'approved'),
                $this->q('What does VDI stand for in virtualization?', [$this->correct('Virtual Desktop Infrastructure'), $this->wrong('Virtual Data Integration'), $this->wrong('Virtual Device Interface'), $this->wrong('Virtual Disk Image')], 'VDI hosts desktop environments on centralized servers, allowing users to access their desktops from any device.', 'medium', 'approved'),
                $this->q('Which virtualization technology allows containers to run applications with shared OS kernels?', [$this->correct('Docker'), $this->wrong('VMware'), $this->wrong('Hyper-V'), $this->wrong('VirtualBox')], 'Docker uses containerization to package applications with their dependencies, sharing the host OS kernel for efficiency.', 'hard', 'approved'),
                $this->q('What is a snapshot in virtualization?', [$this->correct('A point-in-time copy of a VM\'s state'), $this->wrong('A screenshot of the VM'), $this->wrong('A performance metric'), $this->wrong('A backup schedule')], 'A snapshot captures the entire state of a virtual machine at a specific point in time, allowing easy rollback.', 'medium', 'approved'),
                $this->q('Which cloud storage service is provided by Amazon Web Services?', [$this->correct('Amazon S3'), $this->wrong('Azure Blob Storage'), $this->wrong('Google Cloud Storage'), $this->wrong('Dropbox')], 'Amazon S3 (Simple Storage Service) is AWS\'s object storage service for storing and retrieving data.', 'easy', 'approved'),
                $this->q('What is the purpose of resource pooling in cloud computing?', [$this->correct('Share computing resources among multiple users'), $this->wrong('Backup data'), $this->wrong('Encrypt data'), $this->wrong('Monitor performance')], 'Resource pooling allows cloud providers to serve multiple customers using a multi-tenant model with dynamically assigned resources.', 'medium', 'approved'),
                $this->q('Which term describes the ability to quickly scale cloud resources up or down?', [$this->correct('Elasticity'), $this->wrong('Virtualization'), $this->wrong('Redundancy'), $this->wrong('Encryption')], 'Elasticity allows cloud resources to be rapidly scaled up or down based on demand, a key benefit of cloud computing.', 'easy', 'approved'),
                $this->q('What does SaaS stand for?', [$this->correct('Software as a Service'), $this->wrong('Server as a Service'), $this->wrong('Storage as a Service'), $this->wrong('Security as a Service')], 'SaaS delivers software applications over the internet on a subscription basis, like Office 365 or Gmail.', 'easy', 'approved'),
                $this->q('Which hypervisor is developed by Microsoft?', [$this->correct('Hyper-V'), $this->wrong('VMware ESXi'), $this->wrong('KVM'), $this->wrong('Xen')], 'Hyper-V is Microsoft\'s Type 1 hypervisor included with Windows Server and some Windows client editions.', 'easy', 'approved'),
                $this->q('What is the primary advantage of a hybrid cloud deployment?', [$this->correct('Flexibility to use both private and public cloud resources'), $this->wrong('Lowest cost'), $this->wrong('Fastest performance'), $this->wrong('Simplest management')], 'Hybrid cloud combines private and public clouds, allowing data and applications to move between them for flexibility.', 'medium', 'approved'),
                $this->q('Which cloud characteristic allows users to access resources from anywhere with internet connectivity?', [$this->correct('Broad network access'), $this->wrong('Resource pooling'), $this->wrong('Rapid elasticity'), $this->wrong('Measured service')], 'Broad network access means cloud resources are available over the network from various client devices.', 'easy', 'approved'),
                $this->q('What is the purpose of a virtual switch in virtualization?', [$this->correct('Network connectivity between VMs and physical network'), $this->wrong('Power management'), $this->wrong('Storage allocation'), $this->wrong('CPU scheduling')], 'A virtual switch connects virtual machines to each other and to the physical network infrastructure.', 'medium', 'approved'),
                $this->q('Which cloud service model requires the least management from the customer?', [$this->correct('SaaS'), $this->wrong('IaaS'), $this->wrong('PaaS'), $this->wrong('All require equal management')], 'SaaS requires the least customer management as the provider handles infrastructure, platform, and application maintenance.', 'medium', 'approved'),
                $this->q('What does VM stand for in virtualization?', [$this->correct('Virtual Machine'), $this->wrong('Virtual Memory'), $this->wrong('Virtual Monitor'), $this->wrong('Virtual Module')], 'A Virtual Machine is a software emulation of a physical computer that runs an operating system and applications.', 'easy', 'approved'),
                $this->q('Which AWS service provides virtual servers in the cloud?', [$this->correct('EC2'), $this->wrong('S3'), $this->wrong('Lambda'), $this->wrong('RDS')], 'Amazon EC2 (Elastic Compute Cloud) provides resizable virtual servers (instances) in the AWS cloud.', 'medium', 'approved'),
                $this->q('What is the purpose of cloud bursting?', [$this->correct('Temporarily use public cloud when private cloud capacity is exceeded'), $this->wrong('Backup data to cloud'), $this->wrong('Distribute traffic across servers'), $this->wrong('Encrypt cloud data')], 'Cloud bursting allows applications to run in private cloud and burst to public cloud when demand exceeds private cloud capacity.', 'hard', 'approved'),
                $this->q('Which virtualization feature allows moving a running VM from one host to another without downtime?', [$this->correct('Live migration'), $this->wrong('Snapshot'), $this->wrong('Clone'), $this->wrong('Replication')], 'Live migration (or vMotion in VMware) moves running VMs between hosts with no downtime for maintenance or load balancing.', 'hard', 'approved'),
                $this->q('What is a container in cloud computing?', [$this->correct('A lightweight, portable package containing an application and its dependencies'), $this->wrong('A storage unit for data'), $this->wrong('A virtual machine'), $this->wrong('A cloud backup solution')], 'Containers package applications with their dependencies, sharing the host OS kernel for efficiency and portability.', 'medium', 'approved'),
                $this->q('Which cloud provider offers Azure services?', [$this->correct('Microsoft'), $this->wrong('Amazon'), $this->wrong('Google'), $this->wrong('IBM')], 'Microsoft Azure is Microsoft\'s cloud computing platform offering IaaS, PaaS, and SaaS services.', 'easy', 'approved'),
                $this->q('What is the purpose of load balancing in cloud computing?', [$this->correct('Distribute traffic across multiple servers'), $this->wrong('Reduce costs'), $this->wrong('Encrypt data'), $this->wrong('Backup data')], 'Load balancing distributes incoming network traffic across multiple servers to ensure reliability and performance.', 'medium', 'approved'),
                $this->q('Which term describes paying only for cloud resources you actually use?', [$this->correct('Pay-as-you-go/Measured service'), $this->wrong('Resource pooling'), $this->wrong('Elasticity'), $this->wrong('Virtualization')], 'Cloud computing uses a pay-as-you-go model where customers pay only for the resources they consume.', 'easy', 'approved'),
                $this->q('What is the primary security concern with public cloud deployments?', [$this->correct('Data privacy and multi-tenancy'), $this->wrong('Cost'), $this->wrong('Performance'), $this->wrong('Scalability')], 'Public clouds share infrastructure among multiple tenants, raising concerns about data privacy and isolation.', 'medium', 'approved'),
                $this->q('Which virtualization component manages the allocation of physical resources to VMs?', [$this->correct('Hypervisor'), $this->wrong('Guest OS'), $this->wrong('Virtual switch'), $this->wrong('Container engine')], 'The hypervisor manages and allocates physical resources (CPU, memory, storage) to virtual machines.', 'medium', 'approved'),
                $this->q('What is serverless computing?', [$this->correct('Cloud model where provider manages server infrastructure'), $this->wrong('Computing without physical servers'), $this->wrong('Peer-to-peer computing'), $this->wrong('Edge computing')], 'Serverless computing (like AWS Lambda) allows developers to run code without managing servers; the provider handles infrastructure.', 'hard', 'approved'),
                $this->q('Which cloud storage type is best for frequently accessed data requiring low latency?', [$this->correct('Hot storage'), $this->wrong('Archive storage'), $this->wrong('Cold storage'), $this->wrong('Warm storage')], 'Hot storage (or standard storage) is optimized for frequently accessed data with low latency requirements.', 'medium', 'approved'),
            ],
            
            'Hardware and Network Troubleshooting' => [
                // Original 3 questions
                $this->q('A computer repeatedly shuts down after a few minutes of use. What is the most likely cause?', [$this->correct('Overheating due to failed cooling system'), $this->wrong('Software virus'), $this->wrong('Incorrect BIOS settings'), $this->wrong('Bad RAM')], 'Repeated shutdowns after brief operation typically indicate overheating. Check CPU fan, heatsink, and thermal paste.', 'medium', 'approved'),
                $this->q('A user cannot connect to the network. The link light on the NIC is off. What should you check first?', [$this->correct('Cable connection and cable integrity'), $this->wrong('IP address configuration'), $this->wrong('Firewall settings'), $this->wrong('DNS settings')], 'No link light indicates a physical layer problem. Check cable connections, cable damage, and switch port before troubleshooting higher layers.', 'easy', 'approved'),
                $this->q('What does POST stand for?', [$this->correct('Power-On Self-Test'), $this->wrong('Program Operating System Test'), $this->wrong('Processor Operating Speed Test'), $this->wrong('Primary Output System Test')], 'POST is a diagnostic testing sequence run by the BIOS when the computer is powered on to verify hardware functionality.', 'easy', 'approved'),
                
                // New 30 questions
                $this->q('A computer repeatedly shuts down after a few minutes of use. What is the most likely cause?', [$this->correct('Overheating CPU'), $this->wrong('Faulty RAM'), $this->wrong('Corrupted operating system'), $this->wrong('Failing hard drive')], 'Repeated shutdowns after brief operation typically indicate thermal shutdown due to CPU overheating from inadequate cooling.', 'medium', 'approved'),
                $this->q('A user cannot connect to the network. The link light on the NIC is off. What should you check first?', [$this->correct('Network cable connection'), $this->wrong('IP configuration'), $this->wrong('Firewall settings'), $this->wrong('DNS settings')], 'No link light indicates a physical layer issue, most commonly a disconnected or faulty cable.', 'easy', 'approved'),
                $this->q('What does POST stand for in computer troubleshooting?', [$this->correct('Power On Self-Test'), $this->wrong('Power On System Test'), $this->wrong('Processor Operating System Test'), $this->wrong('Primary Output System Test')], 'POST is a diagnostic testing sequence run by the BIOS/UEFI when the computer is powered on to check hardware.', 'easy', 'approved'),
                $this->q('A computer displays a "No bootable device" error. What is the most likely cause?', [$this->correct('Failed hard drive or incorrect boot order'), $this->wrong('Faulty RAM'), $this->wrong('Overheating CPU'), $this->wrong('Disconnected monitor')], 'This error indicates the BIOS cannot find a bootable drive, due to drive failure or incorrect boot sequence.', 'medium', 'approved'),
                $this->q('What tool would you use to test network cable continuity?', [$this->correct('Cable tester'), $this->wrong('Multimeter'), $this->wrong('Loopback plug'), $this->wrong('Crimper')], 'A cable tester checks for continuity, proper wiring, and shorts in network cables.', 'medium', 'approved'),
                $this->q('A user reports their computer is running very slowly. What should you check first?', [$this->correct('Task Manager for resource usage'), $this->wrong('BIOS version'), $this->wrong('Hard drive manufacturer'), $this->wrong('Monitor resolution')], 'Task Manager shows CPU, memory, and disk usage, helping identify resource bottlenecks causing slow performance.', 'easy', 'approved'),
                $this->q('What does a continuous beep pattern during POST typically indicate?', [$this->correct('RAM failure'), $this->wrong('Successful boot'), $this->wrong('Hard drive error'), $this->wrong('Keyboard error')], 'Continuous beeping during POST commonly indicates RAM issues, though exact patterns vary by BIOS manufacturer.', 'medium', 'approved'),
                $this->q('A printer is printing blank pages. What is the most likely cause?', [$this->correct('Empty or clogged ink/toner cartridge'), $this->wrong('Paper jam'), $this->wrong('Network connectivity issue'), $this->wrong('Corrupted driver')], 'Blank pages typically indicate empty ink/toner cartridges or clogged print heads in inkjet printers.', 'medium', 'approved'),
                $this->q('What command would you use to release and renew a DHCP IP address in Windows?', [$this->correct('ipconfig /release and ipconfig /renew'), $this->wrong('ipconfig /flushdns'), $this->wrong('netstat -r'), $this->wrong('ping localhost')], 'ipconfig /release releases the current IP, and ipconfig /renew requests a new IP from the DHCP server.', 'medium', 'approved'),
                $this->q('A user\'s wireless connection keeps dropping. What should you check first?', [$this->correct('Distance from access point and signal strength'), $this->wrong('Hard drive health'), $this->wrong('RAM capacity'), $this->wrong('CPU temperature')], 'Weak signal due to distance, obstacles, or interference is the most common cause of dropped wireless connections.', 'medium', 'approved'),
                $this->q('What does the Blue Screen of Death (BSOD) in Windows typically indicate?', [$this->correct('Critical system error'), $this->wrong('Successful update'), $this->wrong('Low disk space'), $this->wrong('Antivirus scan')], 'BSOD indicates a critical system error that caused Windows to crash, often due to hardware or driver issues.', 'easy', 'approved'),
                $this->q('A computer won\'t power on and there are no lights or sounds. What should you check first?', [$this->correct('Power cable and outlet'), $this->wrong('RAM seating'), $this->wrong('BIOS settings'), $this->wrong('Hard drive connection')], 'No power at all suggests an issue with the power supply, cable, or outlet before checking internal components.', 'easy', 'approved'),
                $this->q('What tool measures electrical voltage, current, and resistance?', [$this->correct('Multimeter'), $this->wrong('Cable tester'), $this->wrong('Loopback plug'), $this->wrong('Toner probe')], 'A multimeter is used to measure voltage, current, and resistance for diagnosing electrical issues.', 'easy', 'approved'),
                $this->q('A user reports seeing artifacts and distortion on their monitor. What is the likely cause?', [$this->correct('Failing graphics card or driver issue'), $this->wrong('Keyboard malfunction'), $this->wrong('Network connectivity problem'), $this->wrong('Low disk space')], 'Visual artifacts typically indicate graphics card failure, overheating, or corrupted display drivers.', 'medium', 'approved'),
                $this->q('What does the command "ping 127.0.0.1" test?', [$this->correct('TCP/IP stack functionality'), $this->wrong('Internet connectivity'), $this->wrong('DNS resolution'), $this->wrong('Router connectivity')], 'Pinging 127.0.0.1 (loopback address) tests if the TCP/IP stack is properly installed and functioning.', 'medium', 'approved'),
                $this->q('A laptop battery drains very quickly. What should you check?', [$this->correct('Battery health and background processes'), $this->wrong('Screen resolution'), $this->wrong('Keyboard layout'), $this->wrong('Mouse settings')], 'Battery drain can be caused by battery degradation or resource-intensive background processes.', 'medium', 'approved'),
                $this->q('What does the "tracert" command do?', [$this->correct('Shows the path packets take to reach a destination'), $this->wrong('Tests cable continuity'), $this->wrong('Displays IP configuration'), $this->wrong('Releases DHCP lease')], 'Tracert (traceroute) shows each hop a packet takes to reach its destination, useful for diagnosing routing issues.', 'medium', 'approved'),
                $this->q('A computer makes a clicking sound from the hard drive. What does this indicate?', [$this->correct('Imminent hard drive failure'), $this->wrong('Normal operation'), $this->wrong('Fan malfunction'), $this->wrong('RAM error')], 'Clicking sounds from a hard drive (click of death) indicate mechanical failure and imminent drive failure.', 'medium', 'approved'),
                $this->q('What is the purpose of Safe Mode in Windows troubleshooting?', [$this->correct('Boot with minimal drivers to troubleshoot issues'), $this->wrong('Increase performance'), $this->wrong('Enable all features'), $this->wrong('Update drivers automatically')], 'Safe Mode loads only essential drivers and services, helping isolate software and driver problems.', 'easy', 'approved'),
                $this->q('A user cannot print to a network printer. What should you verify first?', [$this->correct('Network connectivity to the printer'), $this->wrong('Printer firmware version'), $this->wrong('Paper size settings'), $this->wrong('Toner levels')], 'Network connectivity should be verified first using ping or checking if other users can print to the same printer.', 'easy', 'approved'),
                $this->q('What does the "nslookup" command do?', [$this->correct('Queries DNS to resolve domain names'), $this->wrong('Shows network statistics'), $this->wrong('Tests network speed'), $this->wrong('Displays routing table')], 'Nslookup queries DNS servers to troubleshoot DNS resolution issues and verify domain name mappings.', 'medium', 'approved'),
                $this->q('A computer freezes randomly during use. What are the most likely causes?', [$this->correct('Overheating, faulty RAM, or driver issues'), $this->wrong('Monitor settings'), $this->wrong('Keyboard malfunction'), $this->wrong('Incorrect time settings')], 'Random freezes are commonly caused by overheating, bad RAM, incompatible drivers, or software conflicts.', 'medium', 'approved'),
                $this->q('What does a flashing LED on a network switch port indicate?', [$this->correct('Network activity/data transmission'), $this->wrong('Port failure'), $this->wrong('Power issue'), $this->wrong('Configuration error')], 'A flashing LED indicates active data transmission through that port, while steady light shows connection without activity.', 'easy', 'approved'),
                $this->q('A user reports no sound from their computer. What should you check first?', [$this->correct('Volume settings and mute status'), $this->wrong('Graphics card'), $this->wrong('Network connection'), $this->wrong('BIOS version')], 'Check basic settings first: volume level, mute status, and correct audio output device selection.', 'easy', 'approved'),
                $this->q('What does the "netstat" command display?', [$this->correct('Active network connections and listening ports'), $this->wrong('Hard drive statistics'), $this->wrong('CPU usage'), $this->wrong('Memory allocation')], 'Netstat shows active network connections, listening ports, and network statistics for troubleshooting.', 'medium', 'approved'),
                $this->q('A laptop screen is very dim. What is the most likely cause?', [$this->correct('Failing backlight or inverter'), $this->wrong('Keyboard malfunction'), $this->wrong('Hard drive failure'), $this->wrong('Network issue')], 'Dim screens on laptops typically indicate backlight or inverter failure, especially if brightness controls don\'t help.', 'medium', 'approved'),
                $this->q('What does the "sfc /scannow" command do in Windows?', [$this->correct('Scans and repairs corrupted system files'), $this->wrong('Scans for viruses'), $this->wrong('Checks disk for errors'), $this->wrong('Updates drivers')], 'System File Checker (sfc /scannow) scans for and attempts to repair corrupted Windows system files.', 'medium', 'approved'),
                $this->q('A computer displays "CMOS checksum error" on boot. What should you do?', [$this->correct('Replace CMOS battery and reconfigure BIOS settings'), $this->wrong('Replace the hard drive'), $this->wrong('Reinstall operating system'), $this->wrong('Replace RAM')], 'CMOS checksum errors indicate BIOS settings corruption, often due to a dead CMOS battery requiring replacement.', 'medium', 'approved'),
                $this->q('What is the purpose of a loopback plug in network troubleshooting?', [$this->correct('Test network port functionality'), $this->wrong('Extend cable length'), $this->wrong('Connect two computers directly'), $this->wrong('Boost network signal')], 'A loopback plug redirects transmitted signals back to the port, testing if the network interface is functioning.', 'hard', 'approved'),
                $this->q('A user reports their USB device is not recognized. What should you try first?', [$this->correct('Try a different USB port or restart the computer'), $this->wrong('Reinstall operating system'), $this->wrong('Replace the motherboard'), $this->wrong('Update BIOS')], 'Simple solutions first: try different USB ports, restart the computer, or test the device on another computer.', 'easy', 'approved'),
            ],
        ];
    }
}

