<?php

namespace Database\Seeders\Questions;

use App\Models\Certification;

/**
 * Supplementary Hard Questions for PMP Certification
 * 
 * This seeder contains 100 additional hard difficulty questions to supplement
 * the main ProjectManagementProfessionalPMPQuestionSeeder.
 * 
 * Distribution:
 * - Project Management Fundamentals: 13 questions
 * - Scope Management: 13 questions
 * - Schedule Management: 13 questions
 * - Cost Management: 13 questions
 * - Quality Management: 11 questions
 * - Risk Management: 13 questions
 * - Stakeholder Management: 12 questions
 * - Agile and Hybrid Approaches: 12 questions
 * 
 * Total: 100 hard questions
 */
class ProjectManagementProfessionalPMPHardQuestionsSupplementary extends BaseQuestionSeeder
{
    protected function getCertificationSlug(): string
    {
        return 'pmp';
    }

    protected function getQuestionsData(): array
    {
        return [
            'Project Management Fundamentals' => [
                $this->q('A project charter is being developed. Who should ideally authorize it?', [$this->correct('A sponsor or initiator external to the project with authority to fund the project'), $this->wrong('The project manager'), $this->wrong('The project team'), $this->wrong('The customer')], 'The project charter should be authorized by a sponsor, program manager, or PMO representative with authority to commit organizational resources, not the PM who is often assigned through the charter itself.', 'hard', 'approved'),
                $this->q('What is the primary difference between a project and operations?', [$this->correct('Projects are temporary with unique deliverables; operations are ongoing with repetitive outputs'), $this->wrong('Projects are more important'), $this->wrong('Operations have no objectives'), $this->wrong('Projects never end')], 'Projects create unique products, services, or results and are temporary. Operations sustain the organization through ongoing, repetitive activities.', 'hard', 'approved'),
                $this->q('How does organizational structure impact project success?', [$this->correct('It determines PM authority, resource availability, and communication patterns'), $this->wrong('It has no impact'), $this->wrong('Only affects large projects'), $this->wrong('Only affects budget')], 'Organizational structure (functional, matrix, projectized) significantly impacts PM authority, team member availability, resource control, and project communication effectiveness.', 'hard', 'approved'),
                $this->q('What is the relationship between project, program, and portfolio management?', [$this->correct('Projects are grouped into programs for coordinated management; programs and projects are grouped into portfolios for strategic alignment'), $this->wrong('They are all the same'), $this->wrong('Portfolios are smallest'), $this->wrong('Programs contain portfolios')], 'The hierarchy is: Portfolio (strategic alignment) → Program (coordinated benefits) → Project (specific deliverables). Each level serves different organizational objectives.', 'hard', 'approved'),
                $this->q('How should a PM handle a situation where the project charter conflicts with stakeholder expectations?', [$this->correct('Facilitate discussions to align understanding, clarify the charter, and update it through proper change control if needed'), $this->wrong('Ignore stakeholder expectations'), $this->wrong('Ignore the charter'), $this->wrong('Proceed without resolving the conflict')], 'Charter conflicts indicate misalignment that must be resolved early. The PM facilitates resolution through stakeholder engagement and formal change processes.', 'hard', 'approved'),
                $this->q('What is the purpose of a project management information system (PMIS)?', [$this->correct('To provide a standardized environment for project management tools, processes, and information'), $this->wrong('To replace the project manager'), $this->wrong('To eliminate documentation'), $this->wrong('Only for scheduling')], 'PMIS integrates tools for scheduling, cost control, resource management, and communication, providing a centralized platform for project information and collaboration.', 'hard', 'approved'),
                $this->q('How does enterprise environmental factors (EEFs) influence project planning?', [$this->correct('EEFs are external conditions (market, regulations, culture) that constrain or direct project decisions'), $this->wrong('EEFs are internal only'), $this->wrong('EEFs can be changed by the PM'), $this->wrong('EEFs are not relevant')], 'EEFs include organizational culture, market conditions, regulations, and infrastructure that the PM must consider but cannot control, influencing all project processes.', 'hard', 'approved'),
                $this->q('What is the difference between organizational process assets and enterprise environmental factors?', [$this->correct('OPAs are internal knowledge and processes the organization can control; EEFs are conditions the organization cannot control'), $this->wrong('They are the same'), $this->wrong('EEFs are controllable'), $this->wrong('OPAs are external')], 'OPAs (templates, lessons learned, policies) are organizational knowledge assets. EEFs (regulations, market, culture) are environmental conditions. OPAs can be updated; EEFs must be accommodated.', 'hard', 'approved'),
                $this->q('How does the project life cycle relate to the product life cycle?', [$this->correct('A product life cycle may include multiple project life cycles across its conception, growth, maturity, and decline phases'), $this->wrong('They are identical'), $this->wrong('Product life cycle is shorter'), $this->wrong('They are unrelated')], 'Product life cycles span from concept to retirement, often involving multiple projects (development, enhancement, maintenance) each with their own project life cycle.', 'hard', 'approved'),
                $this->q('What is the role of the project management office (PMO)?', [$this->correct('To standardize project governance, provide support, training, and oversight across projects'), $this->wrong('To manage all projects directly'), $this->wrong('To replace project managers'), $this->wrong('Only for documentation')], 'PMOs provide varying levels of support from providing templates and training (supportive) to direct management (directive), ensuring organizational PM standards and strategic alignment.', 'hard', 'approved'),
                $this->q('How should a PM balance competing demands of scope, schedule, cost, quality, resources, and risk?', [$this->correct('Through stakeholder engagement, trade-off analysis, and transparent communication about impacts of decisions'), $this->wrong('Always prioritize cost'), $this->wrong('Always prioritize schedule'), $this->wrong('Ignore some constraints')], 'The PM must facilitate stakeholder decision-making by analyzing and communicating trade-offs among competing constraints, as optimizing one often impacts others.', 'hard', 'approved'),
                $this->q('What is the difference between predictive and adaptive project life cycles?', [$this->correct('Predictive plans upfront with sequential phases; adaptive plans iteratively with frequent feedback'), $this->wrong('They are the same'), $this->wrong('Predictive is always better'), $this->wrong('Adaptive has no planning')], 'Predictive (waterfall) suits well-defined requirements with detailed upfront planning. Adaptive (agile) suits uncertainty with iterative planning and delivery.', 'hard', 'approved'),
                $this->q('How does project governance support project success?', [$this->correct('It provides the framework for decision-making, accountability, and oversight aligned with organizational strategy'), $this->wrong('It slows down projects'), $this->wrong('It is only for large projects'), $this->wrong('It eliminates the need for a PM')], 'Project governance establishes decision rights, accountability, performance criteria, and escalation paths, ensuring projects deliver value and align with organizational objectives.', 'hard', 'approved'),
            ],
            
            'Scope Management' => [
                $this->q('A stakeholder requests a feature that is out of scope. The PM determines it adds significant value. What is the best course of action?', [$this->correct('Submit a formal change request through integrated change control, including impact analysis'), $this->wrong('Add it immediately since it adds value'), $this->wrong('Reject it because it is out of scope'), $this->wrong('Add it without documentation')], 'Even valuable changes must follow formal change control to assess impacts on scope, schedule, cost, quality, and other constraints, and obtain proper approval.', 'hard', 'approved'),
                $this->q('What is the relationship between the scope baseline and the project management plan baseline?', [$this->correct('The scope baseline is one component of the performance measurement baseline, along with schedule and cost baselines'), $this->wrong('They are the same'), $this->wrong('The scope baseline contains the PM plan'), $this->wrong('They are unrelated')], 'The performance measurement baseline integrates scope, schedule, and cost baselines to measure project performance; the scope baseline consists of the scope statement, WBS, and WBS dictionary.', 'hard', 'approved'),
                $this->q('How should a PM handle gold plating?', [$this->correct('Prevent it by clearly defining acceptance criteria and educating the team that unapproved extras waste resources'), $this->wrong('Encourage it to delight customers'), $this->wrong('Allow it if it does not cost extra time'), $this->wrong('Ignore it')], 'Gold plating (adding unasked-for features) wastes resources, can introduce defects, delays delivery, and may not align with actual customer needs or priorities.', 'hard', 'approved'),
                $this->q('What is the critical difference between validate scope and control quality?', [$this->correct('Validate scope focuses on acceptance of deliverables; control quality focuses on correctness of deliverables'), $this->wrong('They are the same process'), $this->wrong('Control quality comes first'), $this->wrong('Validate scope checks correctness')], 'Control quality verifies deliverables meet quality requirements (correctness), while validate scope obtains formal acceptance from customers/sponsors (acceptance). Quality typically precedes validation.', 'hard', 'approved'),
                $this->q('A project has a detailed WBS but stakeholders are confused about deliverables. What is likely missing?', [$this->correct('The WBS dictionary providing detailed descriptions of each WBS component'), $this->wrong('More WBS levels'), $this->wrong('The project schedule'), $this->wrong('The budget')], 'The WBS dictionary complements the WBS by providing detailed information about each component, including descriptions, deliverables, milestones, and acceptance criteria.', 'hard', 'approved'),
                $this->q('How does requirements traceability support project success?', [$this->correct('It links requirements to business objectives and deliverables, ensuring nothing is missed and managing scope changes'), $this->wrong('It makes documentation longer'), $this->wrong('It slows down the project'), $this->wrong('It is only for compliance')], 'Requirements traceability ensures all requirements are addressed, helps assess change impacts, supports testing and validation, and maintains alignment with business objectives.', 'hard', 'approved'),
                $this->q('What is the relationship between user stories and the WBS in a hybrid project?', [$this->correct('User stories can be decomposed into WBS work packages for detailed planning and tracking'), $this->wrong('They cannot coexist'), $this->wrong('User stories replace the WBS'), $this->wrong('WBS replaces user stories')], 'In hybrid approaches, user stories (agile) can be integrated into WBS structure (predictive) to combine iterative delivery with comprehensive scope management.', 'hard', 'approved'),
                $this->q('A customer accepts a deliverable during validate scope but later claims it does not meet needs. What likely failed?', [$this->correct('Requirements elicitation and validation during planning, or acceptance criteria were unclear'), $this->wrong('The deliverable quality'), $this->wrong('The project schedule'), $this->wrong('The budget')], 'This indicates requirements were not properly understood, documented, or validated with stakeholders, or acceptance criteria were ambiguous, leading to misaligned expectations.', 'hard', 'approved'),
                $this->q('How should a PM handle scope definition when requirements are highly uncertain?', [$this->correct('Use an adaptive lifecycle with iterative requirements elaboration and frequent customer feedback'), $this->wrong('Guess all requirements upfront'), $this->wrong('Wait until requirements are certain'), $this->wrong('Skip scope definition')], 'High uncertainty favors adaptive approaches where requirements are progressively elaborated through iterations, prototypes, and continuous stakeholder engagement.', 'hard', 'approved'),
                $this->q('What is the impact of poor scope definition on project success?', [$this->correct('Increased changes, rework, cost overruns, schedule delays, and stakeholder dissatisfaction'), $this->wrong('No impact if the team is good'), $this->wrong('Only affects documentation'), $this->wrong('Only affects the planning phase')], 'Poor scope definition is a leading cause of project failure, resulting in misaligned expectations, frequent changes, wasted effort, and inability to measure success.', 'hard', 'approved'),
                $this->q('How does the concept of minimum viable product (MVP) relate to scope management?', [$this->correct('MVP defines minimum scope to deliver value, enabling early feedback and reducing waste'), $this->wrong('MVP means poor quality'), $this->wrong('MVP is the full scope'), $this->wrong('MVP only applies to startups')], 'MVP focuses on essential features that deliver core value, allowing early market validation, faster time-to-value, and informed decisions about additional scope.', 'hard', 'approved'),
                $this->q('What is the relationship between product backlog refinement and scope management?', [$this->correct('Refinement progressively elaborates and prioritizes scope, similar to rolling wave planning'), $this->wrong('They are unrelated'), $this->wrong('Refinement replaces scope management'), $this->wrong('Scope management is only for waterfall')], 'Backlog refinement is an ongoing scope management activity in agile, where requirements are continuously detailed, estimated, and prioritized based on value and learning.', 'hard', 'approved'),
                $this->q('A project scope statement is approved, but the customer later says they will know it when they see it. How should the PM respond?', [$this->correct('Implement iterative development with frequent demonstrations and feedback loops to progressively define requirements'), $this->wrong('Proceed with the approved scope statement'), $this->wrong('Tell the customer they must define requirements now'), $this->wrong('Cancel the project')], 'This situation requires an adaptive approach with prototypes, mockups, or working increments to elicit and validate requirements through demonstration rather than documentation alone.', 'hard', 'approved'),
            ],
            
            'Schedule Management' => [
                $this->q('A project critical path is 120 days. Activity X has 10 days of free float and 15 days of total float. What does this indicate?', [$this->correct('Activity X is not on the critical path and has flexibility without affecting successor or project completion'), $this->wrong('Activity X is on the critical path'), $this->wrong('Activity X will delay the project'), $this->wrong('Free float and total float are always equal')], 'Free float is the time an activity can be delayed without delaying early start of successors; total float is without delaying project. The difference indicates successors have their own float.', 'hard', 'approved'),
                $this->q('Using three-point estimating, an activity has optimistic=4, most likely=8, pessimistic=18 days. What is the PERT estimate?', [$this->correct('(4 + 4×8 + 18) / 6 = 9 days'), $this->wrong('8 days'), $this->wrong('10 days'), $this->wrong('7 days')], 'PERT uses weighted average: (O + 4M + P) / 6. This gives more weight to the most likely estimate while accounting for uncertainty.', 'hard', 'approved'),
                $this->q('What is the primary difference between leads and lags in schedule development?', [$this->correct('Leads accelerate successor activities; lags delay successor activities'), $this->wrong('They are the same thing'), $this->wrong('Leads delay; lags accelerate'), $this->wrong('Both delay activities')], 'Leads allow overlap (negative lag), starting successors before predecessors finish. Lags add waiting time between activities (positive lag).', 'hard', 'approved'),
                $this->q('A project has SPI=0.75 and CPI=1.10. What should the PM focus on?', [$this->correct('Schedule performance, as the project is significantly behind schedule despite being under budget'), $this->wrong('Cost performance'), $this->wrong('Both equally'), $this->wrong('Neither, performance is acceptable')], 'SPI < 1.0 indicates behind schedule (only 75% of planned work complete). While under budget (CPI > 1.0), schedule recovery is the priority.', 'hard', 'approved'),
                $this->q('How does resource leveling affect the project schedule?', [$this->correct('It often extends the project duration by resolving resource over-allocation'), $this->wrong('It always shortens the schedule'), $this->wrong('It has no effect on duration'), $this->wrong('It only affects cost')], 'Resource leveling smooths resource usage by delaying activities, which can extend the critical path and project duration to eliminate over-allocation.', 'hard', 'approved'),
                $this->q('What is the difference between crashing and fast tracking?', [$this->correct('Crashing adds resources to shorten duration; fast tracking overlaps activities'), $this->wrong('They are the same'), $this->wrong('Fast tracking adds resources'), $this->wrong('Crashing overlaps activities')], 'Crashing increases cost to reduce time (more resources). Fast tracking increases risk by doing parallel work, potentially at no extra cost.', 'hard', 'approved'),
                $this->q('In critical chain method, what is the purpose of buffers?', [$this->correct('To protect the project schedule from uncertainty without padding individual activities'), $this->wrong('To waste time'), $this->wrong('To extend the project'), $this->wrong('To increase cost')], 'Critical chain removes safety time from individual estimates and aggregates it into buffers (project, feeding, resource) to protect against variability.', 'hard', 'approved'),
                $this->q('A project baseline shows completion in 100 days. After 40 days, 30% is complete. What is the SPI?', [$this->correct('SPI = 0.30 / 0.40 = 0.75 (behind schedule)'), $this->wrong('SPI = 1.0'), $this->wrong('SPI = 1.33'), $this->wrong('SPI = 0.30')], 'SPI = EV / PV. After 40% of time, only 30% of work is done, indicating the project is behind schedule.', 'hard', 'approved'),
                $this->q('How should a PM handle a critical path activity that is delayed?', [$this->correct('Analyze options: crash, fast track, reduce scope, or accept delay; then implement approved corrective action'), $this->wrong('Immediately add more resources'), $this->wrong('Cancel the project'), $this->wrong('Ignore it')], 'Critical path delays require analysis of alternatives, impact assessment, and stakeholder decision-making to determine the best recovery approach.', 'hard', 'approved'),
                $this->q('What is the relationship between the schedule baseline and schedule forecasts?', [$this->correct('The baseline is the approved plan; forecasts predict future performance based on current trends'), $this->wrong('They are the same'), $this->wrong('Forecasts never change'), $this->wrong('Baselines are updated daily')], 'The baseline is fixed (changed only through change control), while forecasts are updated regularly based on actual performance and remaining work.', 'hard', 'approved'),
                $this->q('In agile, how does velocity relate to schedule planning?', [$this->correct('Velocity is the average story points completed per iteration, used to forecast future sprint capacity'), $this->wrong('Velocity measures speed only'), $this->wrong('Velocity is not used for planning'), $this->wrong('Velocity is the same as productivity')], 'Velocity (empirical measure of team output) enables data-driven sprint planning and release forecasting based on historical performance.', 'hard', 'approved'),
                $this->q('What is Monte Carlo simulation used for in schedule management?', [$this->correct('To model the probability of different schedule outcomes by running many iterations with variable inputs'), $this->wrong('To create the initial schedule'), $this->wrong('To replace the project manager'), $this->wrong('To eliminate all risks')], 'Monte Carlo uses probability distributions for activity durations, running thousands of simulations to determine likelihood of meeting schedule targets.', 'hard', 'approved'),
                $this->q('How does the concept of rolling wave planning support schedule management in uncertain environments?', [$this->correct('It allows detailed planning for near-term work while keeping future work at higher level until more information is available'), $this->wrong('It means no planning is needed'), $this->wrong('It only applies to agile'), $this->wrong('It eliminates all uncertainty')], 'Rolling wave planning balances the need for detailed planning with the reality of uncertainty, progressively elaborating the schedule as the project unfolds.', 'hard', 'approved'),
            ],
            
            'Cost Management' => [
                $this->q('A project has BAC=$500K, EV=$200K, AC=$250K. What is the EAC assuming current variances are typical?', [$this->correct('EAC = BAC / CPI = $500K / 0.8 = $625K'), $this->wrong('$500K'), $this->wrong('$550K'), $this->wrong('$750K')], 'When current cost performance is expected to continue, EAC = BAC / CPI. CPI = EV/AC = 200/250 = 0.8, so EAC = 500/0.8 = 625K.', 'hard', 'approved'),
                $this->q('What is the difference between cost baseline and project budget?', [$this->correct('Cost baseline is time-phased; project budget includes management reserves'), $this->wrong('They are identical'), $this->wrong('Budget is always smaller'), $this->wrong('Baseline includes reserves')], 'Cost baseline is the approved time-phased budget (excludes management reserves). Project budget adds management reserves for unknown risks.', 'hard', 'approved'),
                $this->q('A project has CPI=0.90 and SPI=0.85. What is the TCPI to complete within BAC?', [$this->correct('TCPI = (BAC - EV) / (BAC - AC), indicating required future efficiency'), $this->wrong('0.90'), $this->wrong('0.85'), $this->wrong('1.0')], 'TCPI shows the cost performance index needed for remaining work to meet BAC. With poor current performance, future efficiency must improve significantly.', 'hard', 'approved'),
                $this->q('How does Earned Value Management integrate scope, schedule, and cost?', [$this->correct('EV measures work accomplished in monetary terms, enabling comparison with planned value (schedule) and actual cost'), $this->wrong('It only measures cost'), $this->wrong('It replaces the project plan'), $this->wrong('It is only for large projects')], 'EVM provides objective performance measurement by comparing planned work (PV), completed work value (EV), and actual cost (AC) in common units.', 'hard', 'approved'),
                $this->q('What is the purpose of a cost management plan?', [$this->correct('To define how project costs will be planned, structured, estimated, budgeted, and controlled'), $this->wrong('To list all costs'), $this->wrong('To approve the budget'), $this->wrong('To reduce costs')], 'The cost management plan establishes the framework for cost management processes, including level of accuracy, units of measure, and control thresholds.', 'hard', 'approved'),
                $this->q('A project has three options: NPV of $50K, $75K, and $60K. Which should be selected?', [$this->correct('The option with NPV=$75K, as it provides the highest net present value'), $this->wrong('The first option'), $this->wrong('The cheapest option'), $this->wrong('All three equally')], 'NPV (Net Present Value) accounts for time value of money. Higher NPV indicates better financial return, making it the preferred selection criterion.', 'hard', 'approved'),
                $this->q('What is the difference between parametric and analogous estimating?', [$this->correct('Parametric uses statistical relationships; analogous uses historical data from similar projects'), $this->wrong('They are the same'), $this->wrong('Analogous is more accurate'), $this->wrong('Parametric does not use data')], 'Parametric estimating uses mathematical models (e.g., cost per square foot). Analogous uses expert judgment based on similar past projects.', 'hard', 'approved'),
                $this->q('How should a PM handle a negative cost variance?', [$this->correct('Analyze root causes, develop corrective actions, and implement approved changes to bring costs back in line'), $this->wrong('Ignore it if schedule is good'), $this->wrong('Always add more budget'), $this->wrong('Blame the team')], 'Negative CV (over budget) requires root cause analysis, impact assessment, and corrective action through integrated change control.', 'hard', 'approved'),
                $this->q('What is the relationship between reserves and risk management?', [$this->correct('Contingency reserves address known risks; management reserves address unknown risks'), $this->wrong('Reserves are not related to risks'), $this->wrong('All reserves are the same'), $this->wrong('Reserves eliminate risks')], 'Contingency reserves are estimated for identified risks (part of cost baseline). Management reserves are for unidentified risks (not in baseline).', 'hard', 'approved'),
                $this->q('In a fixed-price contract, who bears the cost risk?', [$this->correct('The seller bears cost risk, as they must deliver for the agreed price regardless of actual costs'), $this->wrong('The buyer'), $this->wrong('Both equally'), $this->wrong('No one')], 'Fixed-price contracts transfer cost risk to the seller, incentivizing efficient delivery. The buyer cost is predictable.', 'hard', 'approved'),
                $this->q('What is life cycle costing?', [$this->correct('Considering total cost of ownership including acquisition, operating, maintenance, and disposal costs'), $this->wrong('Only initial project costs'), $this->wrong('Only operating costs'), $this->wrong('Only disposal costs')], 'Life cycle costing ensures decisions consider long-term financial impact, not just initial investment, leading to better value.', 'hard', 'approved'),
                $this->q('How does value engineering support cost management?', [$this->correct('It finds ways to reduce costs while maintaining or improving quality and performance'), $this->wrong('It reduces quality to cut costs'), $this->wrong('It only increases costs'), $this->wrong('It is not related to cost')], 'Value engineering systematically analyzes functions to achieve necessary performance at lowest total cost without sacrificing quality.', 'hard', 'approved'),
                $this->q('A project has BAC=$400K, AC=$300K, EV=$250K. The remaining work is expected to be more difficult. How should EAC be calculated?', [$this->correct('EAC = AC + (BAC - EV) / (CPI × SPI) or AC + bottom-up estimate of remaining work'), $this->wrong('EAC = BAC / CPI'), $this->wrong('EAC = BAC'), $this->wrong('EAC = AC + BAC')], 'When future performance is expected to differ from past, use combined performance index or re-estimate remaining work rather than assuming current trends continue.', 'hard', 'approved'),
            ],
            
            'Quality Management' => [
                $this->q('A control chart shows 7 consecutive points above the mean. What does this indicate?', [$this->correct('The process is out of control due to non-random variation (Rule of Seven)'), $this->wrong('The process is performing well'), $this->wrong('The process is in control'), $this->wrong('The mean should be raised')], 'The Rule of Seven states that seven consecutive points on one side of the mean indicate special cause variation, requiring investigation and corrective action.', 'hard', 'approved'),
                $this->q('What is the difference between precision and accuracy in quality management?', [$this->correct('Precision is consistency of measurements; accuracy is correctness relative to true value'), $this->wrong('They are the same'), $this->wrong('Accuracy is consistency'), $this->wrong('Precision is correctness')], 'Precision means repeated measurements are close to each other (low variation). Accuracy means measurements are close to the true value (low bias). Both are needed for quality.', 'hard', 'approved'),
                $this->q('How does the cost of quality framework support project decision-making?', [$this->correct('It quantifies prevention, appraisal, and failure costs to optimize quality investment'), $this->wrong('It eliminates all quality costs'), $this->wrong('It only tracks failure costs'), $this->wrong('It is not used for decisions')], 'COQ analysis shows that investing in prevention and appraisal reduces total quality costs by preventing expensive internal and external failures.', 'hard', 'approved'),
                $this->q('What is the relationship between quality assurance and quality control?', [$this->correct('QA is process-focused and preventive; QC is product-focused and detective'), $this->wrong('They are the same'), $this->wrong('QC is preventive'), $this->wrong('QA inspects products')], 'QA audits processes to prevent defects (process improvement). QC inspects deliverables to detect defects (product verification). Both are essential.', 'hard', 'approved'),
                $this->q('A Pareto chart shows 80% of defects come from 3 out of 15 causes. What should the PM do?', [$this->correct('Focus improvement efforts on the top 3 causes for maximum impact'), $this->wrong('Address all 15 causes equally'), $this->wrong('Ignore the other 12 causes'), $this->wrong('Create a new chart')], 'The Pareto Principle (80/20 rule) guides prioritization: focus on the vital few causes that create most problems for efficient improvement.', 'hard', 'approved'),
                $this->q('How does statistical sampling support quality control?', [$this->correct('It enables cost-effective inspection by testing a representative subset rather than 100% inspection'), $this->wrong('It eliminates the need for inspection'), $this->wrong('It is less accurate than 100% inspection'), $this->wrong('It only works for large batches')], 'Statistical sampling uses probability theory to draw valid conclusions about a population from a sample, balancing cost and confidence.', 'hard', 'approved'),
                $this->q('What is the purpose of a quality audit?', [$this->correct('To determine if project activities comply with organizational and project policies, processes, and procedures'), $this->wrong('To find defects in deliverables'), $this->wrong('To punish the team'), $this->wrong('To delay the project')], 'Quality audits are structured, independent reviews that identify best practices, gaps, and improvement opportunities in process execution.', 'hard', 'approved'),
                $this->q('How does Six Sigma relate to quality management?', [$this->correct('It is a data-driven methodology to reduce defects to 3.4 per million opportunities'), $this->wrong('It is a type of control chart'), $this->wrong('It means six quality checks'), $this->wrong('It is only for manufacturing')], 'Six Sigma uses DMAIC (Define, Measure, Analyze, Improve, Control) to achieve near-perfect quality (99.99966% defect-free).', 'hard', 'approved'),
                $this->q('What is the difference between validation and verification?', [$this->correct('Validation ensures the right product is built; verification ensures the product is built right'), $this->wrong('They are the same'), $this->wrong('Verification checks customer needs'), $this->wrong('Validation checks specifications')], 'Verification checks conformance to specifications (are we building it right?). Validation checks fitness for use (are we building the right thing?).', 'hard', 'approved'),
                $this->q('How should a PM handle a situation where quality and schedule are in conflict?', [$this->correct('Analyze trade-offs, present options to stakeholders, and make informed decisions based on priorities and long-term impact'), $this->wrong('Always choose quality'), $this->wrong('Always choose schedule'), $this->wrong('Compromise both equally')], 'The PM must facilitate stakeholder decision-making by presenting impacts of each option, considering cost of poor quality, reputation, and strategic implications.', 'hard', 'approved'),
                $this->q('What is the relationship between continuous improvement and quality management?', [$this->correct('Continuous improvement (Kaizen, PDCA) is an ongoing effort to incrementally improve processes and products'), $this->wrong('They are unrelated'), $this->wrong('Continuous improvement is a one-time effort'), $this->wrong('Quality management prevents improvement')], 'Continuous improvement (Plan-Do-Check-Act cycle) drives incremental enhancements, fostering a culture of quality and learning.', 'hard', 'approved'),
            ],
            
            'Risk Management' => [
                $this->q('A project has three risks: Risk A (P=0.7, Impact=$100K), Risk B (P=0.3, Impact=$200K), Risk C (P=0.5, Impact=$80K). What is the total EMV?', [$this->correct('$170K (70K + 60K + 40K)'), $this->wrong('$380K'), $this->wrong('$127K'), $this->wrong('$100K')], 'Expected Monetary Value (EMV) = Probability × Impact. Sum all EMVs: (0.7×100K) + (0.3×200K) + (0.5×80K) = 70K + 60K + 40K = 170K.', 'hard', 'approved'),
                $this->q('What is the difference between a threat and an issue?', [$this->correct('A threat is an uncertain future event that may negatively impact the project; an issue is a current problem'), $this->wrong('They are the same'), $this->wrong('Issues are future; threats are current'), $this->wrong('Threats are always worse')], 'Threats are risks (uncertain events) managed proactively through risk management. Issues are current problems managed reactively through issue management.', 'hard', 'approved'),
                $this->q('How does Monte Carlo simulation support risk analysis?', [$this->correct('It models the combined effect of all risks by running thousands of simulations with probability distributions'), $this->wrong('It eliminates all risks'), $this->wrong('It identifies new risks'), $this->wrong('It is only for schedule risks')], 'Monte Carlo simulation quantifies overall project risk by combining individual risk probability distributions, showing likelihood of meeting objectives.', 'hard', 'approved'),
                $this->q('What is the difference between qualitative and quantitative risk analysis?', [$this->correct('Qualitative prioritizes risks by probability and impact; quantitative numerically analyzes their effect on objectives'), $this->wrong('They are the same'), $this->wrong('Quantitative is always better'), $this->wrong('Qualitative uses numbers')], 'Qualitative analysis uses probability and impact matrix for prioritization. Quantitative analysis uses techniques like EMV and Monte Carlo for numerical analysis.', 'hard', 'approved'),
                $this->q('A risk has been accepted. What should the PM do?', [$this->correct('Document the decision, assign a risk owner to monitor it, and establish triggers for potential response'), $this->wrong('Forget about it'), $this->wrong('Immediately implement a response'), $this->wrong('Escalate to the sponsor')], 'Accepted risks require documentation, monitoring, and contingency planning. Active acceptance includes reserves; passive acceptance acknowledges without specific action.', 'hard', 'approved'),
                $this->q('How does risk appetite influence risk management decisions?', [$this->correct('It defines the degree of uncertainty stakeholders are willing to accept in pursuit of objectives'), $this->wrong('It has no influence'), $this->wrong('It eliminates all risks'), $this->wrong('It only applies to opportunities')], 'Risk appetite (organizational tolerance for risk) guides risk response strategies, determining which risks to accept, avoid, mitigate, or transfer.', 'hard', 'approved'),
                $this->q('What is the purpose of a risk breakdown structure?', [$this->correct('To organize and categorize risks hierarchically to ensure comprehensive identification'), $this->wrong('To eliminate risks'), $this->wrong('To prioritize risks'), $this->wrong('To assign risk owners')], 'The RBS provides a framework for systematic risk identification across categories (technical, external, organizational, project management), ensuring nothing is overlooked.', 'hard', 'approved'),
                $this->q('How should a PM handle a risk that has occurred?', [$this->correct('Implement the contingency plan, document lessons learned, and update the risk register'), $this->wrong('Panic'), $this->wrong('Ignore it'), $this->wrong('Blame someone')], 'When risks occur, execute planned responses, assess effectiveness, implement workarounds if needed, and capture lessons learned for future projects.', 'hard', 'approved'),
                $this->q('What is the relationship between assumptions and risks?', [$this->correct('Assumptions are factors believed true but carry risk if proven false; they should be analyzed as potential risks'), $this->wrong('They are unrelated'), $this->wrong('Assumptions eliminate risks'), $this->wrong('Risks eliminate assumptions')], 'Assumptions analysis examines the validity of assumptions and identifies risks if they prove incorrect, converting implicit risks into explicit ones.', 'hard', 'approved'),
                $this->q('How does risk tolerance differ from risk threshold?', [$this->correct('Tolerance is the acceptable degree of variation; threshold is the specific point triggering a response'), $this->wrong('They are the same'), $this->wrong('Threshold is broader than tolerance'), $this->wrong('Neither affects risk management')], 'Risk tolerance defines the acceptable range of variation around objectives. Risk thresholds are specific levels that trigger escalation or response.', 'hard', 'approved'),
                $this->q('What is the purpose of risk reassessment?', [$this->correct('To regularly review identified risks, evaluate response effectiveness, and identify new risks as the project evolves'), $this->wrong('To create the initial risk register'), $this->wrong('A one-time activity'), $this->wrong('To eliminate all risks')], 'Risk reassessment is iterative, recognizing that risk profiles change as the project progresses, new information emerges, and responses are implemented.', 'hard', 'approved'),
                $this->q('How should opportunity risks be managed differently from threat risks?', [$this->correct('Use exploit, enhance, share, or accept strategies to maximize positive impacts'), $this->wrong('Ignore opportunities'), $this->wrong('Use the same strategies as threats'), $this->wrong('Opportunities do not need management')], 'Opportunity management uses positive risk strategies: exploit (ensure it happens), enhance (increase probability/impact), share (partner), or accept (take if it occurs).', 'hard', 'approved'),
                $this->q('What is the value of risk audits?', [$this->correct('They evaluate the effectiveness of risk responses and the risk management process'), $this->wrong('They identify new risks'), $this->wrong('They eliminate risks'), $this->wrong('They are not valuable')], 'Risk audits examine how well risk responses are working, whether risk management processes are being followed, and identify improvements for current and future projects.', 'hard', 'approved'),
            ],
            
            'Stakeholder Management' => [
                $this->q('A key stakeholder is actively resisting the project. What should the PM do first?', [$this->correct('Understand the root cause of resistance through one-on-one discussion and address underlying concerns'), $this->wrong('Escalate to the sponsor immediately'), $this->wrong('Ignore the stakeholder'), $this->wrong('Remove them from the project')], 'Resistance often stems from unaddressed concerns, lack of involvement, or misalignment. Understanding and addressing root causes is more effective than escalation.', 'hard', 'approved'),
                $this->q('How does the salience model differ from the power/interest grid?', [$this->correct('Salience considers power, legitimacy, and urgency; power/interest only considers power and interest'), $this->wrong('They are the same'), $this->wrong('Power/interest is more comprehensive'), $this->wrong('Salience only considers power')], 'The salience model adds legitimacy (rightful involvement) and urgency (time sensitivity) to power, providing a more nuanced stakeholder classification.', 'hard', 'approved'),
                $this->q('What is the relationship between stakeholder engagement and project success?', [$this->correct('Effective stakeholder engagement increases support, reduces resistance, and improves decision-making, directly impacting success'), $this->wrong('They are unrelated'), $this->wrong('Stakeholder engagement wastes time'), $this->wrong('Project success is independent of stakeholders')], 'Research shows stakeholder engagement is a critical success factor, influencing requirements quality, change acceptance, and overall project support.', 'hard', 'approved'),
                $this->q('How should a PM handle conflicting stakeholder expectations?', [$this->correct('Facilitate negotiation, find common ground, prioritize based on business value, and document agreements'), $this->wrong('Choose the most powerful stakeholder expectations'), $this->wrong('Try to satisfy everyone equally'), $this->wrong('Ignore the conflict')], 'Conflict resolution requires facilitation, active listening, finding win-win solutions, and making trade-offs transparent and documented.', 'hard', 'approved'),
                $this->q('What is the purpose of the stakeholder engagement assessment matrix?', [$this->correct('To compare current engagement levels with desired levels and plan strategies to close gaps'), $this->wrong('To list all stakeholders'), $this->wrong('To rank stakeholders'), $this->wrong('To eliminate stakeholders')], 'The engagement assessment matrix identifies gaps between current state (Unaware, Resistant, Neutral, Supportive, Leading) and desired state, guiding targeted engagement strategies.', 'hard', 'approved'),
                $this->q('How does cultural awareness support stakeholder management?', [$this->correct('It enables effective communication and relationship-building across diverse cultural contexts'), $this->wrong('It is not relevant'), $this->wrong('It only applies to international projects'), $this->wrong('It complicates stakeholder management')], 'Cultural awareness helps PMs understand different communication styles, decision-making processes, and values, enabling more effective stakeholder engagement.', 'hard', 'approved'),
                $this->q('What is the difference between managing and engaging stakeholders?', [$this->correct('Engagement is proactive and collaborative; managing implies control and can be perceived negatively'), $this->wrong('They are the same'), $this->wrong('Managing is better'), $this->wrong('Engagement is passive')], 'Modern PM emphasizes stakeholder engagement (partnership, collaboration) over management (control), recognizing stakeholders as partners in success.', 'hard', 'approved'),
                $this->q('How should a PM handle a stakeholder who is supportive but has low power?', [$this->correct('Keep them informed and leverage their support to influence others'), $this->wrong('Ignore them due to low power'), $this->wrong('Spend maximum time with them'), $this->wrong('Escalate their power')], 'Supportive stakeholders, even with low power, can be advocates, provide valuable input, and influence others. Keeping them informed maintains their support.', 'hard', 'approved'),
                $this->q('What is the role of emotional intelligence in stakeholder management?', [$this->correct('It enables PMs to recognize, understand, and manage emotions in themselves and stakeholders for better relationships'), $this->wrong('It is not relevant'), $this->wrong('It only applies to team management'), $this->wrong('It complicates stakeholder management')], 'Emotional intelligence (self-awareness, self-regulation, empathy, social skills) is critical for building trust, managing conflict, and influencing stakeholders.', 'hard', 'approved'),
                $this->q('How does stakeholder analysis support communication planning?', [$this->correct('It identifies stakeholder information needs, preferred communication methods, and frequency to tailor communications'), $this->wrong('It eliminates the need for communication'), $this->wrong('It is unrelated to communication'), $this->wrong('It standardizes all communication')], 'Stakeholder analysis informs communication planning by identifying who needs what information, when, how, and from whom, enabling targeted, effective communication.', 'hard', 'approved'),
                $this->q('What is the impact of stakeholder turnover on the project?', [$this->correct('It can disrupt relationships, change requirements, and require re-engagement efforts'), $this->wrong('It has no impact'), $this->wrong('It always improves the project'), $this->wrong('It only affects documentation')], 'Stakeholder turnover requires proactive management: updating the stakeholder register, re-establishing relationships, and ensuring new stakeholders understand context and commitments.', 'hard', 'approved'),
                $this->q('How should a PM balance stakeholder demands with project constraints?', [$this->correct('Transparently communicate trade-offs, facilitate prioritization, and manage expectations based on the triple constraint'), $this->wrong('Accept all demands'), $this->wrong('Reject all demands'), $this->wrong('Ignore constraints')], 'Effective stakeholder management requires honest communication about constraints, collaborative prioritization, and managing expectations through transparency and education.', 'hard', 'approved'),
            ],
            
            'Agile and Hybrid Approaches' => [
                $this->q('How does the Scrum Master role differ from a traditional project manager?', [$this->correct('Scrum Master is a servant leader facilitating the team; PM has more directive authority'), $this->wrong('They are identical'), $this->wrong('PM has no authority'), $this->wrong('Scrum Master manages scope')], 'Scrum Masters serve the team by removing impediments and coaching agile practices, while traditional PMs have more directive control over scope, schedule, and resources.', 'hard', 'approved'),
                $this->q('What is the purpose of a sprint retrospective?', [$this->correct('For the team to inspect their process and identify improvements for the next sprint'), $this->wrong('To review the product'), $this->wrong('To plan the next sprint'), $this->wrong('To report to stakeholders')], 'The retrospective focuses on process improvement (what went well, what did not, what to improve), fostering continuous improvement and team empowerment.', 'hard', 'approved'),
                $this->q('How does Definition of Done support quality in agile?', [$this->correct('It establishes a shared understanding of completion criteria, ensuring consistent quality standards'), $this->wrong('It eliminates testing'), $this->wrong('It slows down delivery'), $this->wrong('It is not related to quality')], 'Definition of Done creates transparency and accountability by defining quality criteria (coded, tested, documented, integrated) that must be met before work is considered complete.', 'hard', 'approved'),
                $this->q('What is the difference between sprint planning and release planning?', [$this->correct('Sprint planning focuses on the next iteration; release planning focuses on multiple sprints toward a release goal'), $this->wrong('They are the same'), $this->wrong('Release planning is more detailed'), $this->wrong('Sprint planning is strategic')], 'Sprint planning is tactical (what can we deliver this sprint?). Release planning is strategic (what features for which release, when?), providing a roadmap.', 'hard', 'approved'),
                $this->q('How does velocity support agile planning?', [$this->correct('It measures team capacity empirically, enabling data-driven sprint commitment and release forecasting'), $this->wrong('It measures individual performance'), $this->wrong('It is not used for planning'), $this->wrong('It eliminates estimation')], 'Velocity (story points completed per sprint) provides empirical data for capacity planning, helping teams commit to realistic sprint goals and forecast release dates.', 'hard', 'approved'),
                $this->q('What is the purpose of timeboxing in agile?', [$this->correct('To create focus, limit work in progress, and force prioritization by setting fixed durations'), $this->wrong('To waste time'), $this->wrong('To extend deadlines'), $this->wrong('To eliminate planning')], 'Timeboxing (fixed-duration sprints, meetings) creates urgency, forces prioritization of high-value work, and provides regular cadence for feedback and adaptation.', 'hard', 'approved'),
                $this->q('How does a hybrid approach combine predictive and adaptive methods?', [$this->correct('It uses predictive planning for well-defined work and adaptive delivery for uncertain work'), $this->wrong('It never works'), $this->wrong('It only uses one method'), $this->wrong('It eliminates all planning')], 'Hybrid approaches leverage strengths of both: predictive for stable requirements and governance, adaptive for innovation and customer feedback, tailored to project context.', 'hard', 'approved'),
                $this->q('What is the role of the product owner in Scrum?', [$this->correct('To maximize product value by managing the backlog, prioritizing features, and accepting work'), $this->wrong('To manage the team'), $this->wrong('To write all code'), $this->wrong('To facilitate ceremonies')], 'The Product Owner represents stakeholders, defines and prioritizes the backlog, makes trade-off decisions, and accepts completed work, ensuring the team builds the right thing.', 'hard', 'approved'),
                $this->q('How does continuous integration support agile delivery?', [$this->correct('It enables frequent integration of code changes, detecting conflicts early and maintaining a releasable product'), $this->wrong('It eliminates testing'), $this->wrong('It slows down development'), $this->wrong('It is only for large teams')], 'Continuous integration (automated build and test on each commit) provides rapid feedback, reduces integration risk, and supports sustainable pace and quality.', 'hard', 'approved'),
                $this->q('What is the difference between Scrum and Kanban?', [$this->correct('Scrum uses fixed-length sprints with defined roles; Kanban is flow-based with continuous delivery'), $this->wrong('They are identical'), $this->wrong('Kanban has sprints'), $this->wrong('Scrum has no roles')], 'Scrum is iterative with timeboxed sprints, ceremonies, and roles. Kanban is continuous flow with WIP limits and pull-based delivery, both are agile but suit different contexts.', 'hard', 'approved'),
                $this->q('How does user story mapping support release planning?', [$this->correct('It visualizes user journey and features, helping prioritize MVPs and plan incremental releases'), $this->wrong('It replaces the backlog'), $this->wrong('It is only for documentation'), $this->wrong('It eliminates planning')], 'User story mapping arranges stories by user workflow and priority, making it easier to identify minimum viable product and plan value-driven releases.', 'hard', 'approved'),
                $this->q('What is the purpose of a spike in agile?', [$this->correct('A timeboxed research activity to reduce uncertainty and inform estimates or decisions'), $this->wrong('To delay work'), $this->wrong('To avoid work'), $this->wrong('To create documentation')], 'Spikes are short, focused investigations (technical or functional) to gain knowledge needed for estimation, design decisions, or risk reduction before committing to full implementation.', 'hard', 'approved'),
            ],
        ];
    }
}
